export const form = {
    loginHeader: 'Вход/Регистрация',
    loginText: 'Введите ваш адрес электронной почты для входа. Если пользователя с таким адресом еще нет в системе, вы будете автоматически зарегистрированы.',
    loginButtonLabel:'Войти',
    logoutButtonLabel: 'Выйти',
    emailLabel: 'Email',
    emailPlaceholder: 'Введите ваш адрес электронной почты',
    passwordLabel: 'Пароль',
    passwordPlaceholder: 'Введите ваш пароль',
    newHeader: 'Добавить заметку',
    editHeader: 'Редактировать заметку',
    newText: 'Вы можете добавить тему и текст сообщения, а также прикрепить файлы (их можно просто перетащить в форму)',
    subjectLabel: 'Заголовок',
    subjectPlaceholder: 'Введите заголовок заметки',
    bodyLabel: 'Текст заметки',
    bodyPlaceholder: 'Введите текст заметки',
    addNewButtonLabel: 'Отправить',
    addNewButtonInHeaderLabel: 'Добавить заметку',
    attach: 'Прикрепить файл', 
    areYouSure: 'Вы уверены, что хотите удалить эту заметку?',
    memosHeader: 'Ваши заметки',
    redirect: 'Заметка успешно добавлена. Вы будете перенаправлены',
    enteredAs: 'Вы вошли как ',
} 